const express= require('express');
const routes=require('./router/router');
const port=8006;
const app=express();
const router=express.Router();
routes(router);
app.use(express.json());
app.use(express.urlencoded({extended:false}));
app.use('/',router);
app.listen(port,()=>console.log("Listening " + port));